accrual:
    accrual_system_address: :8081
auth:
    jwt-issuer: gophermart
    jwt-key: my_secret_key
    jwt-token-ttl: 3h
pgsql:
    database_uri: postgres://cl:cl@localhost:5432/gophermart?sslmode=disable
    pool:
        max-idle: 2
        max-idle-time: 30s
        max-lifetime: 30s
        max-open: 100
webserver:
    idle-timeout: 30s
    read-header-timeout: 2s
    read-timeout: 1s
    run_address: :8080
    write-timeout: 1s
