webserver:
  address: ":8080"
  read-timeout: 1s
  write-timeout: 1s
  idle-timeout: 30s
  read-header-timeout: 2s

pgsql:
  dsn: 'postgres://cl:cl@localhost:5432/gophermart?sslmode=disable'
  pool:
    max-open: 100
    max-idle: 2
    max-idle-time: 30s
    max-lifetime: 30s

auth:
  jwt-key: 'my_secret_key'
  jwt-issuer: 'gophermart'
  jwt-token-ttl: 3h