### Ping
GET http://localhost:8080/ping
Content-type: application/json;

### RegisterUser
POST http://localhost:8080/api/user/register
Content-type: application/json;

{
  "username": "max11",
  "password": "true password"
}

### LoginUser
POST http://localhost:8080/api/user/login

{
  "username": "max11",
  "password": "true passwor"
}

### orders/create
POST http://localhost:8080/api/user/orders
Content-Type: text/plain

5181975718047403

### orders/fetch

GET http://localhost:8080/api/user/orders

### balance/fetch

GET http://localhost:8080/api/user/balance